[project]
name = "cut-optimiser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pydantic>=2.11.7",
    "traccc-bench-tools",
]

[tool.uv.sources]
traccc-bench-tools = { path = "../benchmark" }

[dependency-groups]
dev = [
    "black>=25.1.0",
]
